# Generated by Django 6.0.7 on 2026-08-03 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Competencia',
                'verbose_name_plural': 'Competencias',
                'db_table': 'competencies_competency',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subcompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcompetencies', to='competencies.competency', verbose_name='Competencia')),
            ],
            options={
                'verbose_name': 'Subcompetencia',
                'verbose_name_plural': 'Subcompetencias',
                'db_table': 'competencies_subcompetency',
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INICIAL', 'Inicial'), ('EN_DESARROLLO', 'En Desarrollo'), ('COMPETENTE', 'Competente'), ('EXCELENTE', 'Excelente')], max_length=20, verbose_name='Nivel de dominio')),
                ('description', models.TextField(verbose_name='Descripción del nivel')),
                ('min_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Puntaje mínimo')),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Puntaje máximo')),
                ('subcompetency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='competencies.subcompetency', verbose_name='Subcompetencia')),
            ],
            options={
                'verbose_name': 'Rúbrica',
                'verbose_name_plural': 'Rúbricas',
                'db_table': 'competencies_rubric',
                'unique_together': {('subcompetency', 'level')},
            },
        ),
    ]
