# Generated by Django 6.0.7 on 2026-08-03 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Texto de la pregunta')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden de presentación')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está activa?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_questions', to='competencies.competency', verbose_name='Competencia')),
            ],
            options={
                'verbose_name': 'Pregunta de diagnóstico',
                'verbose_name_plural': 'Preguntas de diagnóstico',
                'db_table': 'diagnostics_diagnosticquestion',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Puntuación asignada')),
                ('observation', models.TextField(blank=True, verbose_name='Observación adicional')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de evaluación')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='diagnostics.diagnosticquestion', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Resultado de diagnóstico',
                'verbose_name_plural': 'Resultados de diagnóstico',
                'db_table': 'diagnostics_diagnosticresult',
            },
        ),
    ]
