# Generated by Django 4.2.30 on 2026-08-04 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_session_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_file_size_mb', models.PositiveIntegerField(default=10, verbose_name='Límite de tamaño de archivo (MB)')),
                ('allowed_file_extensions', models.CharField(default='pdf, docx, png, jpg, jpeg, mp4, zip', max_length=200, verbose_name='Extensiones permitidas')),
                ('smtp_host', models.CharField(blank=True, default='smtp.gmail.com', max_length=150, verbose_name='Servidor SMTP')),
                ('smtp_port', models.PositiveIntegerField(default=587, verbose_name='Puerto SMTP')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='Usar TLS para correo')),
                ('system_email', models.EmailField(blank=True, default='notificaciones@sistema.edu.ec', max_length=254, verbose_name='Correo remitente institucional')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Modo mantenimiento')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Parámetro del Sistema',
                'verbose_name_plural': 'Parámetros del Sistema',
                'db_table': 'users_systemsetting',
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Asunto / Título')),
                ('description', models.TextField(verbose_name='Descripción de la incidencia')),
                ('category', models.CharField(choices=[('TECNICO', 'Problema Técnico / Error'), ('CUENTA', 'Acceso y Cuenta'), ('EVALUACIONES', 'Dificultad con Evaluaciones'), ('OTRO', 'Otro / Consulta')], default='TECNICO', max_length=20, verbose_name='Categoría')),
                ('priority', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=10, verbose_name='Prioridad')),
                ('status', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_PROCESO', 'En Proceso'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=15, verbose_name='Estado')),
                ('admin_response', models.TextField(blank=True, verbose_name='Respuesta Administrativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de respuesta/actualización')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Atendido por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Solicitante')),
            ],
            options={
                'verbose_name': 'Ticket de Soporte',
                'verbose_name_plural': 'Tickets de Soporte',
                'db_table': 'users_supportticket',
                'ordering': ['-created_at'],
            },
        ),
    ]
