# Generated by Django 6.0.7 on 2026-08-06 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_systemsetting_supportticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='Nota de seguimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_notes', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_written', to=settings.AUTH_USER_MODEL, verbose_name='Tutor')),
            ],
            options={
                'verbose_name': 'Nota de Tutor',
                'verbose_name_plural': 'Notas de Tutor',
                'db_table': 'users_tutornote',
                'ordering': ['-created_at'],
            },
        ),
    ]
