# Generated by Django 4.2.30 on 2026-08-04 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competencies', '0001_initial'),
        ('activities', '0002_initial'),
        ('evidences', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidences', to='activities.activity', verbose_name='Actividad Formativa'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='external_url',
            field=models.URLField(blank=True, verbose_name='Enlace Externo'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='evidences/%Y/%m/', verbose_name='Archivo Adjunto'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='competency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='competencies.competency', verbose_name='Competencia'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='evidence_type',
            field=models.CharField(choices=[('DOCUMENTO', 'Documento PDF / Word'), ('PRESENTACION', 'Presentación'), ('VIDEO', 'Video'), ('IMAGEN', 'Imagen'), ('ENLACE_EXTERNO', 'Enlace Externo (Drive/YouTube)'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de Evidencia'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='review_comment',
            field=models.TextField(blank=True, verbose_name='Retroalimentación'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_evidences', to=settings.AUTH_USER_MODEL, verbose_name='Revisado Por'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CORREGIR', 'Solicitar Corrección')], default='PENDIENTE', max_length=20, verbose_name='Estado de Revisión'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga'),
        ),
    ]
