# Generated by Django 6.0.7 on 2026-08-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='Acción')),
                ('model_name', models.CharField(max_length=100, verbose_name='Nombre del modelo')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID del objeto')),
                ('changes', models.JSONField(default=dict, verbose_name='Cambios realizados')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'db_table': 'evaluations_auditlog',
                'ordering': ['-timestamp'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Evaluation360',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('evaluation_type', models.CharField(choices=[('AUTOEVALUACION', 'Autoevaluación'), ('PARES', 'Evaluación por Pares'), ('DOCENTE', 'Evaluación por Docente'), ('EMPLEADOR', 'Evaluación por Empleador'), ('TUTOR', 'Evaluación por Tutor')], max_length=20, verbose_name='Tipo de evaluación')),
                ('period', models.CharField(max_length=50, verbose_name='Período académico')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha límite')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Evaluación 360°',
                'verbose_name_plural': 'Evaluaciones 360°',
                'db_table': 'evaluations_evaluation360',
            },
        ),
        migrations.CreateModel(
            name='EvaluationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Puntuación')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Puntuación de Evaluación',
                'verbose_name_plural': 'Puntuaciones de Evaluación',
                'db_table': 'evaluations_evaluationscore',
            },
        ),
    ]
