# Generated by Django 6.0.7 on 2026-08-03 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competencies', '0001_initial'),
        ('evaluations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='evaluation360',
            name='competency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='competencies.competency', verbose_name='Competencia'),
        ),
        migrations.AddField(
            model_name='evaluation360',
            name='evaluated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_received', to=settings.AUTH_USER_MODEL, verbose_name='Evaluado'),
        ),
        migrations.AddField(
            model_name='evaluation360',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_given', to=settings.AUTH_USER_MODEL, verbose_name='Evaluador'),
        ),
        migrations.AddField(
            model_name='evaluationscore',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='evaluations.evaluation360', verbose_name='Evaluación 360°'),
        ),
        migrations.AddField(
            model_name='evaluationscore',
            name='subcompetency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencies.subcompetency', verbose_name='Subcompetencia'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluationscore',
            unique_together={('evaluation', 'subcompetency')},
        ),
    ]
