# Generated by Django 4.2.30 on 2026-08-04 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduateFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Empresa / Institución de trabajo')),
                ('job_title', models.CharField(max_length=150, verbose_name='Cargo / Puesto')),
                ('relevance_rating', models.PositiveSmallIntegerField(choices=[(1, '1 / 5'), (2, '2 / 5'), (3, '3 / 5'), (4, '4 / 5'), (5, '5 / 5')], verbose_name='Relevancia en el trabajo (1-5)')),
                ('frequency_rating', models.PositiveSmallIntegerField(choices=[(1, '1 / 5'), (2, '2 / 5'), (3, '3 / 5'), (4, '4 / 5'), (5, '5 / 5')], verbose_name='Frecuencia de aplicación (1-5)')),
                ('feedback_text', models.TextField(verbose_name='Comentarios / Retroalimentación sobre la competencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduate_feedbacks', to='competencies.competency', verbose_name='Competencia evaluada')),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduate_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Graduado')),
            ],
            options={
                'verbose_name': 'Retroalimentación de Graduado',
                'verbose_name_plural': 'Retroalimentaciones de Graduados',
                'db_table': 'evaluations_graduatefeedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
