# Generated by Django 6.0.7 on 2026-08-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CohortReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('period', models.CharField(help_text='Período académico', max_length=50)),
                ('report_data', models.JSONField(default=dict, help_text='Datos del reporte')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reporte de Cohorte',
                'verbose_name_plural': 'Reportes de Cohortes',
                'db_table': 'analytics_cohortreport',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('evaluations_count', models.PositiveIntegerField(default=0)),
                ('current_level', models.CharField(choices=[('INICIAL', 'Inicial'), ('EN_DESARROLLO', 'En Desarrollo'), ('COMPETENTE', 'Competente'), ('EXCELENTE', 'Excelente')], default='INICIAL', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Métrica de Estudiante',
                'verbose_name_plural': 'Métricas de Estudiantes',
                'db_table': 'analytics_studentmetric',
            },
        ),
    ]
