# Generated by Django 6.0.7 on 2026-08-03 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField(verbose_name='Instrucciones')),
                ('deliverable_description', models.TextField(verbose_name='Descripción del Entregable')),
                ('due_date', models.DateTimeField(verbose_name='Fecha de Entrega')),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='Puntuación Máxima')),
            ],
            options={
                'verbose_name': 'Desafío',
                'verbose_name_plural': 'Desafíos',
                'db_table': 'activities_challenge',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INSCRITO', 'Inscrito'), ('EN_CURSO', 'En Curso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='INSCRITO', max_length=20, verbose_name='Estado')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inscripción')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Finalización')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'db_table': 'activities_enrollment',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Equipo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'activities_team',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('activity_type', models.CharField(choices=[('TALLER', 'Taller'), ('SEMINARIO', 'Seminario'), ('DESAFIO', 'Desafío'), ('RETO_COLABORATIVO', 'Reto Colaborativo')], max_length=20, verbose_name='Tipo de Actividad')),
                ('max_participants', models.PositiveIntegerField(default=30, verbose_name='Máximo de Participantes')),
                ('start_date', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateTimeField(verbose_name='Fecha de Fin')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lugar o Enlace')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='competencies.competency', verbose_name='Competencia')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'activities_activity',
            },
        ),
    ]
