# Generated by Django 4.2.30 on 2026-08-04 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0003_alter_activity_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_applications', to='activities.activity', verbose_name='Actividad')),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_applications', to=settings.AUTH_USER_MODEL, verbose_name='Graduado')),
            ],
            options={
                'verbose_name': 'Solicitud de Mentor',
                'verbose_name_plural': 'Solicitudes de Mentores',
                'db_table': 'activities_mentorapplication',
                'unique_together': {('graduate', 'activity')},
            },
        ),
    ]
