# Generated by Django 6.0.7 on 2026-08-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('EVALUACION_PENDIENTE', 'Evaluación Pendiente'), ('ACTIVIDAD_ASIGNADA', 'Actividad Asignada'), ('EVIDENCIA_REVISADA', 'Evidencia Revisada'), ('RETROALIMENTACION', 'Retroalimentación'), ('SISTEMA', 'Sistema')], default='SISTEMA', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.URLField(blank=True, help_text='Link de acción', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
